---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов 
    nginx-balancer:
      hosts:
        nginx-balancer:
          ansible_host: "{{ nginx_balancer_ip.public }}"
          ansible_local: "{{ nginx_balancer_ip.local }}"
    nginx-server:
      hosts:
        nginx-balancer:
          ansible_host: "{{ nginx_balancer_ip.public }}"
          ansible_local: "{{ nginx_balancer_ip.local }}"
        nginx-server-1:
          ansible_host: "{{ nginx_server_1_ip.public }}"
          ansible_local: "{{ nginx_server_1_ip.local }}"
        nginx-server-2:
          ansible_host: "{{ nginx_server_2_ip.public }}"
          ansible_local: "{{ nginx_server_2_ip.local }}"
    nginx-mediawiki:
      hosts:
        nginx-server-1:
          ansible_host: "{{ nginx_server_1_ip.public }}"
          ansible_local: "{{ nginx_server_1_ip.local }}"
        nginx-server-2:
          ansible_host: "{{ nginx_server_2_ip.public }}"
          ansible_local: "{{ nginx_server_2_ip.local }}"
    nginx-server-1:
      hosts:
        nginx-server-1:
          ansible_host: "{{ nginx_server_1_ip.public }}"
          ansible_local: "{{ nginx_server_1_ip.local }}"
    nginx-server-2:
      hosts:
        nginx-server-2:
          ansible_host: "{{ nginx_server_2_ip.public }}"
          ansible_local: "{{ nginx_server_2_ip.local }}"
    postgresql:
      hosts:
        postgresql-master:
          ansible_host: "{{ postgresql_master_ip.public }}"
          ansible_local: "{{ postgresql_master_ip.local }}"
        postgresql-replica:
          ansible_host: "{{ postgresql_replica_ip.public }}"
          ansible_local: "{{ postgresql_replica_ip.local }}"
    postgresql-master:
      hosts:
        postgresql-master:
          ansible_host: "{{ postgresql_master_ip.public }}"
          ansible_local: "{{ postgresql_master_ip.local }}"
    postgresql-replica:
      hosts:
        postgresql-replica:
          ansible_host: "{{ postgresql_replica_ip.public }}"
          ansible_local: "{{ postgresql_replica_ip.local }}"
    backup-server:
      hosts:
        backup-server:
          ansible_host: "{{ backup_server_ip.public }}"
          ansible_local: "{{ backup_server_ip.local }}"
          ansible_backup_user: "{{ backup_server_ip.backup_user }}"
          ansible_backup_password: "{{ backup_server_ip.backup_password }}"

  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: "ubuntu"
    connection_protocol: ssh  # тип подключения
    ansible_become: true  # Становиться ли другим пользователем после подключения
    ansible_become_user: root
    nginx_balancer_ip:
      public: 
      local: 
    nginx_server_1_ip:
      public: 
      local: 
    nginx_server_2_ip:
      public: 
      local:
    postgresql_master_ip:
      public: 
      local:
    backup_server_ip:
      public:
      local: 
      backup_user: "backup_user"
      backup_password: "backup_password"
    postgresql_replica_ip:
      public: 
      local:
